### ISSUE TITLE
Can't get lib from Nuget console in asp.net web application (.NET Framework)

### ISSUE THREAD

**Issue by HolyFraud** [MagicTheGathering/mtg-sdk-dotnet#19]
Here is the console details:

PM> Install-Package MtgApiManager.Lib

Attempting to gather dependency information for package 'MtgApiManager.Lib.1.2.1' with respect to project 'mtgtest', targeting '.NETFramework,Version=v4.0'
Gathering dependency information took 0.14 ms
Attempting to resolve dependencies for package 'MtgApiManager.Lib.1.2.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'MtgApiManager.Lib.1.2.1'
Resolved actions to install package 'MtgApiManager.Lib.1.2.1'
Retrieving package 'MtgApiManager.Lib 1.2.1' from 'nuget.org'.

Install failed. Rolling back...
Package 'MtgApiManager.Lib.1.2.1' does not exist in project 'mtgtest'
Package 'MtgApiManager.Lib.1.2.1' does not exist in folder 
'C:\Users\User\source\repos\mtgtest\packages'

Executing nuget actions took 162.32 ms

Install-Package : Could not install package 'MtgApiManager.Lib 1.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package MtgApiManager.Lib
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.4577250

**Comment by jregnier** [comment]
The package supports the .Net standard, therefore, your .Net framework project needs to target .Net 4.6.1. Or just create your project targeting the standard, see link below
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Let me know if this solves your issue

**Comment by HolyFraud** [comment]
Thank you so much. It fixed after targeting .Net 4.6.1.
