### ISSUE TITLE
Unable to query cards by name that includes special character û as in Lim-Dûl.

### ISSUE THREAD

**Issue by TRASHMASTERexe** [MagicTheGathering/mtg-sdk-dotnet#20]
I am not sure if there are other instances of special characters like û in card names, but this seems to be the cause of being unable to query for specific cards with the character in the name. The character appears to work when querying MTGIO directly as such https://api.magicthegathering.io/v1/cards?name=Lim-D%C3%BBl%27s%20Paladin.

I may be doing something wrong when I am querying, but it does not appear to work when I encode the special characters manually and i am unsure of how to proceed from this point (beyond mapping all cards with special characters to their multiverse id which just sounds like a lot of work, to be honest.)

**Comment by TRASHMASTERexe** [comment]
It looks like this is also the case with the ampersand '&'

**Comment by jregnier** [comment]
Hello, I will take a look at this bug this weekend and get back to you, thanks!!

**Comment by jregnier** [comment]
I was able to track down the issue, its issue is the way the query builder was encoding the string. I should have a fix in soon. nice catch 💯

**Comment by jregnier** [comment]
fixed. closing this issue
