### ISSUE TITLE
total number of cards

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#21]
Hi

I'm new to the library and I can't find how to get the total number of cards from a Set instance.
I initialize first so I have all sets as explained in the docs.
Then I loop through all sets and want to get the number of cards of each set but I don't find any variable of a Set that has the total number of cards.

Can somebody help me?

**Comment by ancientmagicwizard** [comment]
I'm a C# beginner so I could have missed something.

**Comment by ancientmagicwizard** [comment]
Is this something you plan to add?

I personally would like it. In my current program now the number of cards for each set is missing. It takes a while to count them when going through all cards (and pages).
I don't know if this data is easily extracted from Gatherer without going through all cards like I do now.

It was just an idea. Close the issue if this impossible/not planned.

Thx

**Comment by jregnier** [comment]
the total number of results from a query is in the PagingInfo of the result

**Comment by ancientmagicwizard** [comment]
Yes, but the number of cards of a set are not in the SetService, only in the CardService.
That's what I mean.

**Comment by jregnier** [comment]
I don't have control over this it's part of the Web API, see docs https://docs.magicthegathering.io/#api_v1sets_list

**Comment by ancientmagicwizard** [comment]
Yes, I understand it now.
