### ISSUE TITLE
Set enumerator missing

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#22]
Hi

I want to loop through all cards of a specific set, after getting the set by running the code explained in the docs:

Find a set by code:

SetService service = new SetService();
var result = service.Find("ktk");

So the code I try to run to loop through all cards of 'result' set is:

**foreach (Card card in result.Value)
 {
         //do something with the card
}**

I get the following error:

**Error	CS1579	foreach statement cannot operate on variables of type 'Set' because 'Set' does not contain a public instance or extension definition for 'GetEnumerator'**	

I'm a C# beginner and can't implement this enumerator myself.

Would it be possible to add a Set enumator so it's possible to get all cards of a Set?

What is the default way now to get all cards of a set (without this enumerator)? 

best regards

**Comment by jregnier** [comment]
you are using the wrong service. You need to use the CardService with a query.
cardService.Where(x => x.Set, "ktk");
