### ISSUE TITLE
CardService not returning all cards

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#23]
Hi

Thanks for pointing me to the right CardService. But unfortunately I still don't have the desired result.
I want to get all cards of a specific card set: in the example below I try to print to the screen all cards from set "4ED".

            CardService cardService = new CardService()
            Exceptional<List<Card>> result = cardService.Where(x => x.Set, "4ED").All();
            if (result.IsSuccess)
            {
                List<Card> CardsList = result.Value;

                foreach(Card card in CardsList)
                {
                    Debug.WriteLine(card.Name);
                }
            }
            else
            {
                var exception = result.Exception;
            }

There are 100 cards print to the screen but the list ends when it reaches card with name "Earthquake".
The 4ED has 379 cards while I only get 100 cards.

Is this a bug or what am I doing wrong?
I don't find documenation of the library so I don't know what I'm doing wrong.

Is it maybe possible to write some examples on how to use the library correctly?

Best regards

**Comment by jregnier** [comment]
This is a wrapper around https://docs.magicthegathering.io/
If you take a look at the docs it's all later out for you. There is a limit of 100 per request so you need to page through to get them all

**Comment by ancientmagicwizard** [comment]
I understand what you are saying and looked at the docs there but not specific there about this issue (I think).
Unfortunately I have no idea what to change/add in my code to get the remaining cards (so I don't know the solution considering my code).

Would it be possible for you to change my code part above so it gets all cards and paste the changed code below?

thank you very much!

**Comment by jregnier** [comment]
you can add the paging stuff to the end of the query. Then look at the PagingInfo to see how many pages there are

`                       var currentPage = 1;
                        var totalPages = 0;

                        do
                        {
                            var cardResult = await service
                                .Where(x => x.Set, "4ED")
                                .Where(x => x.Page, currentPage)
                                .Where(x => x.PageSize, 100)
                                .AllAsync();

                            if (cardResult.IsSuccess)
                            {
                                foreach (var card in cardResult.Value)
                                {
                                    System.Diagnostics.Debug.WriteLine(card.Name);
                                }

                                // set the total number of pages only after the first call.
                                if (currentPage == 1)
                                {
                                    totalPages = cardResult.PagingInfo.TotalPages;
                                }

                                currentPage++;
                            }
                        }
                        while (currentPage <= totalPages);`

**Comment by ancientmagicwizard** [comment]
Thank you for the code!

I was wondering: maybe it would be a good idea in a future version to hide the paging from the user?
I think many users will struggle with this, certainly when you're new to it.

Maybe you can make a method that returns a card list but with the paging stuff done internally?
So the method returns all cards for a query and the user does not have to deal with paging.
If possible of course.

Thx for the great library. I enjoy it a lot!

**Comment by ancientmagicwizard** [comment]
Is it normal the looping through the pages takes some time?
Is it just the Gatherer server responding slow or is it maybe a problem in the library I found?
This is no negative comment, just asking myself where the waiting occurs!

I have a fast gaming PC but getting the "4ED" cards just printed to the screen takes 20 seconds.

**Comment by ancientmagicwizard** [comment]
Hi

I tested the code and changed AllAsync() to All() because I don't use the async call.

I found a strange problem: for set "4ED" the cards are printed to the screen and suddenly stop at card "Spirit Link". (the code is finished running)
So still not all cards are printed.

Can you tell me what the problem could be?
I use exactly your code but changed AllAsync() to All() 


thx in advance!

**Comment by jregnier** [comment]
Hello, having a method that returns everything without a way to paging system is always a bad idea, what if the query returns over a million records? It's a pretty common development pattern to contro l that kind of thing expecially in an environment not controlled by the developer.

I ssupect its the server taking some time returning, you can test this by calling the api directly in the browser or a program like postman.

fyi I will be removing the none Async calls in the future version since it's bad practice to have long running methods doing this kind of work not being asynchronous.

it's possible that the number of pages is being calculated wrong, you could try changing the counter to start at page 0 and see what happens?

**Comment by ancientmagicwizard** [comment]
hi

I found it's working with this code. So what's the problem in your code example? I don't really understand since TotalPages is working I think.

            ```
            var cardRequest = cardService.Where(x => x.Set, "4ED");
            Exceptional<List<Card>> result = await cardRequest.AllAsync();

            int pagesCount = result.PagingInfo.TotalPages;
            int cardCount = result.PagingInfo.TotalCount;
            Console.WriteLine("card count:" + cardCount);
            for (int i = 0; i <= pagesCount; i++)
            {
                var page = await cardRequest.Where(p => p.Page, i + 1).AllAsync();
                if (page.IsSuccess)
                {
                    foreach (Card card in page.Value)
                    {
                        Debug.WriteLine(card.Name);                   
                    }
                }
                else
                {
                    throw page.Exception;
                }             
            }
```

**Comment by jregnier** [comment]
that code is basically doing what I suggested since you're index starts at 0

**Comment by ancientmagicwizard** [comment]
Oh yes, oops! :-D
