### ISSUE TITLE
question: .NET Core

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#25]
hi

Is the library also working/tested for .NET Core? That would be great for cross platform use!

I read some developers make a different nuget package for Core, but since I'm no expert , I don't know what problems may occur in Core.

**Comment by jregnier** [comment]
Currently the library is targeting .Net Standard 2.0 which is cross-platform. I am currently working on moving to .net5.0

**Comment by jregnier** [comment]
will release a new version with .Net 5.0, closing this issue
