### ISSUE TITLE
question: set properties

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#26]
Hi

After getting all sets using a setservice and looping through them, I saw for EACH set the 'border' and 'expansion' property has no value. Is this normal or did I found a bug?
So I got 500 sets but none of them has a value for both properties, while for example 'block', 'releasedate', ... are all having a value.

Thx in advance

**Comment by jregnier** [comment]
Try and see if the value is present in a manual call to the API, if so then yes this is a bug

**Comment by ancientmagicwizard** [comment]
Hi

What language is the original API using and where to download it? I only know C#
I only find this: https://docs.magicthegathering.io/#documentationsdks
So I don't find the original API. There is no download link or anything

**Comment by jregnier** [comment]
when I say API I'm referring to a Web API endpoint, not a library. For example, if you put https://api.magicthegathering.io/v1/cards into a browser you will get the result

**Comment by ancientmagicwizard** [comment]
Ah! I had no idea the API was a web API!
I'm not comparing Web API with C# to report (possible) bugs

Can you also give me a link for the 'postman' program?

Thx

**Comment by ancientmagicwizard** [comment]
After comparing to the API, there are no values there too.

**Comment by ancientmagicwizard** [comment]
Can you also give me a link for the 'postman' program?

**Comment by ancientmagicwizard** [comment]
All clear. Closed.
