### ISSUE TITLE
Set: missing 'type'

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#31]
Hi

Since I now know how to use the Web API, I found an important missing variable for a Set. At least, I want to use it in my program to separate core from expansion sets.
The JSON has a 'type' variable which can have value 'core' or 'expansion'. Would it be possible to add this to the Set class as
Set.Type ?

See screenshots. 

![afbeelding](https://user-images.githubusercontent.com/74437452/99416344-0cb3a680-28f9-11eb-8b29-343c435a03e2.png)

![afbeelding](https://user-images.githubusercontent.com/74437452/99416045-b8a8c200-28f8-11eb-95ce-2b5ef9c28973.png)

**Comment by jregnier** [comment]
It doesn't seem to be in the web API docs but I could always add it

**Comment by ancientmagicwizard** [comment]
It's really in the JSON that's returned so the docs are not up to date :-)
I would love to have this added! The separation core/expansion is now missing in my program.
