### ISSUE TITLE
visual studio comments

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#32]
I was also wondering if the comments (in the classes) for each variable or method can be added so it appears in visual studio when selecting a variable or method?
Currently there is no comment in visual studio.

For example in Set class (see text surrounded by **):

        /// <summary>
        /// **Gets the block the set is in.**
        /// </summary>
        public string Block { get; init; }

        /// <summary>
        /// **Gets the booster contents for this set.**
        /// </summary>
        public List<object> Booster { get; init; }

        /// <summary>
        /// **Gets the type of border on the cards, either “white”, “black” or “silver”.**
        /// </summary>
        public string Border { get; init; }

**Comment by ancientmagicwizard** [comment]
I think it's called Intellisense in visual studio. So the automatic selecting of variables and methods and the comments you see on the screen when selecting something.

See screenshot

![afbeelding](https://user-images.githubusercontent.com/74437452/99442253-6926be00-2919-11eb-895e-b7933848e080.png)

**Comment by jregnier** [comment]
the comments should be there so you might have an issue with VS

**Comment by ancientmagicwizard** [comment]
The comments appear in all .NET classes and in all 3rd party libraries I tried, except your library :(

So what can I do to make it work?

**Comment by jregnier** [comment]
Will look into this, it might be something to do with generating the nugget package, when I have a direct reference to the library I see all the comments

**Comment by ancientmagicwizard** [comment]
Thx!
After testing on another PC, I think the problem is not in my visual studio itself.

**Comment by ancientmagicwizard** [comment]
Maybe it's possible to add the 'type' variable at the same time when making a new nuget package (see other issue).
I would love to use this.

**Comment by ancientmagicwizard** [comment]
On google I found a possible solution for this issue. Note I never made any nuget package myself, I just show you this link because I believe this is the solution.

https://stackoverflow.com/questions/40110687/intellisense-and-triple-slash-comments-in-packages

**Comment by jregnier** [comment]
will be in next nuget release, closing issue
