### ISSUE TITLE
question: 2 versions?

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#33]
Hi

Are you planning to make a .Net standard 2.0 and .Net 5.0 separate nuget package?

If you remove the .Net standard 2.0 one I will get into problems because I'm still using .NET Framework 4.

Would it be possible to make 2 nuget packages?

**Comment by ancientmagicwizard** [comment]
Or if possible, a package that can target .Net standard 2.0 and .Net 5.0?

**Comment by ancientmagicwizard** [comment]
The new update with removed JSON.net depency is not showing up on nuget.
Maybe it takes time for it to become online on nuget?

**Comment by jregnier** [comment]
.NET 5 is the new version to rule them all but I was planning on doing a muti release approach (5.0, 2.1 and 2.0)

I haven't created the nugget release yet, I'm planning on other changes before releasing a new package

**Comment by jregnier** [comment]
Closing this issue
