### ISSUE TITLE
Sleep() between service requests needed?

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#34]
Hi,

I was wondering if I need to wait between service (Set or Card) calls in order not to overload the server?

For example If I run multiple async calls in a loop, do I need to wait for example 100 ms (or longer) between them or can I call the one async call after the other in a loop, without waiting between them?

Thx in advance!

**Comment by jregnier** [comment]
no, the library does this for you, check out the rate limit
https://github.com/MagicTheGathering/mtg-sdk-dotnet#rate-limit

**Comment by ancientmagicwizard** [comment]
Thx for the explanation.
