### ISSUE TITLE
MTG Web API contact?

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#35]
Hi

I'm trying to contact the owner of the Web API by using the email on this website: https://andrewbackes.com/
But no answer for months...

I found missing data: some sets have missing multiverse IDs and some even have missing mana cost and original type properties for each card in the set. 

Do you have contact with the owner in order to report this?

thx

**Comment by jregnier** [comment]
no not really sorry

**Comment by jregnier** [comment]
might want to join the discord server and see if that helps, link is on the main site

closing this issue
