### ISSUE TITLE
feature request: CardService Random()

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#36]
Hi

Is it maybe possible to make a Random() method, that when applied on the CardService returns a random Card from a random Set (so just a random card)?
I saw this in a Scryfall C# library and I thought it would be nice for this library too.

Thx

**Comment by jregnier** [comment]
Would most likely need the web API to support this, in order for this library to do this I would need to get all cards then get the random card

**Comment by ancientmagicwizard** [comment]
If you take a random set and inside that set you take a random card, then the resulting card is random too, right?
Then only all cards for that random set must be read.
