### ISSUE TITLE
question: getting card's color

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#39]
Hi

I'm having difficulties in finding the correct way to get a card's (main) color.
A card has 2 variables for color:
 
        /// <summary>
        /// Gets the card colors by color code. [“Red”, “Blue”] becomes [“R”, “U”]
        /// </summary>
        public string[] ColorIdentity { get; init; }

        /// <summary>
        /// Gets the card colors. Usually this is derived from the casting cost, but some cards are special (like the back of dual sided cards and Ghostfire).
        /// </summary>
        public string[] Colors { get; init; }

2 questions:

- Which of those 2 do I need to get the card's color (red, green, black, white or blue)?
Is the main color stored in index 0 of the string array?

- Why is written for ColorIdentity : [“Red”, “Blue”] becomes [“R”, “U”]
Is black represented by "B" but blue by "U" or is this a mistake?

kind regards,
Jessica

**Comment by ancientmagicwizard** [comment]
Found another example in Alliances set: "Energy Arc" with casting cost {W}{U}

The value for card.Colors[0] is Blue.
Why is it not White because this appears first in te casting cost?

**Comment by jregnier** [comment]
this is more of a question about the Web API, I just read in the data as it's given to me. I don't think that it's good programming practice to assume both arrays will be in sync like that

**Comment by ancientmagicwizard** [comment]
Ok I understand

Just to be sure, Black is "B" and Blue is "U", right?

Thx

**Comment by jregnier** [comment]
honestly, I don't know much about the details of MTG

**Comment by ancientmagicwizard** [comment]
So the symbols for each color also just are read from the API, it's not you converting Blue to "U"?

**Comment by jregnier** [comment]
correct

**Comment by ancientmagicwizard** [comment]
Ok understood!
