### ISSUE TITLE
What is the best way to iterate over the pages of cards available ?

### ISSUE THREAD

**Issue by KevM** [MagicTheGathering/mtg-sdk-dotnet#4]
I am enjoying your library but I am finding it tricky to use the pagination as is. 

The controller type is parsing the `Total-Count` header from the result but it seems it is not exposed to the result. Any suggestions for knowing how many pages are present via your library?

**Comment by jregnier** [comment]
Just to make sure I have this correct. Are you looking for the total amount of pages based on your page size? I could always calculate this and add it to the result.

**Comment by KevM** [comment]
Something like this would be great. Either exposing the http headers (like `Total-Count`) directly so requests can react to them and they are not hidden. Or have some sort of pagination details available on the result.

**Comment by jregnier** [comment]
PagingInfo is now in the result

**Comment by KevM** [comment]
Thank you. Can't wait to try it out.

**Comment by GodJohnson** [comment]
Hi,
Just tried PagingInfo, but it's always null.

Am I using it the wrong way ?

```
var service = new CardService();
var result = service.All();

var pagingInfo = result.PagingInfo; 
```

Here, pagingInfo is always null
