### ISSUE TITLE
feature request: Card MultiColor

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#40]
Hi

Is it maybe possible to add a Card property: MultiColor, a boolean?
I would definitely use it :-)

Best regards,
Jessica

**Comment by jregnier** [comment]
do you mean some that just does
`Colors.Count > 1`

**Comment by ancientmagicwizard** [comment]
yes
I think your library can add things not in the original api but usefull?

So it would be usefull if you want to use this for each card so the user of your library don't have to make this if test.

**Comment by jregnier** [comment]
could add this property in the Model

**Comment by ancientmagicwizard** [comment]
Thx a lot!
