### ISSUE TITLE
Can't install version 1.3.0 in .NET Framework 4

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#41]
Hi

I tried to upgrade the nuget package to version 1.3.0 but I get this error. I think you forgot the .NET Framework 4 support?
I can't find another package for  .NET Framework 4.

Could not install package 'MtgApiManager.Lib 1.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ancientmagicwizard** [comment]
Is it maybe possible to create an up to date nuget package for .NET Framework 4 and also one for 5.0 (which already exists now I think: the one in my first message)?
I really love your library and its very easy use, so I want to use it in both .NET versions.

thx in advance!
Jessica

**Comment by jregnier** [comment]
out of curiosity is there a reason you're still using .net 4? I will try and see if I can multi-release. The only thing is that I won't be able to use any of the new C# features

**Comment by ancientmagicwizard** [comment]
There are many reasons to use .NET 4

- a TON of nuget packages don't work in .NET 5.0 yet (I use many)
- the windows forms designer in  .NET 5.0 is still not as fast as .NET 4 and has many bugs 
- many bugs/problems which I don't have in .NET 4

So untill everything is available for .NET 5.0 , I still use .NET 4.

Do you think you can make 1 package for all versions? 

Why do you need new C# features? The library works great.

**Comment by ancientmagicwizard** [comment]
I found some explanation:

https://www.bartwolff.com/Blog/2017/03/20/targeting-multiple-net-platforms-in-a-single-nuget-package-w

**Comment by jregnier** [comment]
I will add .net standard 2.1 as another target which should meet your needs but will need to make some changes, I am going to change the scope of many things so you will need to make some updates in your usage

**Comment by ancientmagicwizard** [comment]
OK! I ask questions if I don't understand.

Will you add All() methods too please?

thx in advance!
Jessica

PS: the .NET 5.0 package works including intellsense comments! I tested it.

**Comment by ancientmagicwizard** [comment]
Hi

I'm curious: why are all the changes suddenly needed?

I don't find MultiColor  property, the issue is closed.
Did you decide not to add this?

**Comment by jregnier** [comment]
I've learned a lot since I first wrote this library so I'm refactoring parts that were poorly made.

IsMultiColor is the property name

**Comment by ancientmagicwizard** [comment]
Ok found it!

Great to hear. I learn/update and ask here if I'm stuck
