### ISSUE TITLE
bug: Set ReleaseDate is empty

### ISSUE THREAD

**Issue by ghost** [MagicTheGathering/mtg-sdk-dotnet#42]
Hi

Did a quick test of my code in .NET 5 (just for testing the updates), but I think I found a bug.
In the previous package all Sets had ReleaseDate filled in, but now they are empty for EACH set.

Can you have a look at it?

I would still like to have a .NET 4 package because I use nuget packages that don't exist yet in .NET 5.

PS: the intellisense comments are working great now!!!

thx

**Comment by ancientmagicwizard** [comment]
FIX THIS OR I KICK YOUR ASS
