### ISSUE TITLE
All() is missing?

### ISSUE THREAD

**Issue by ancientmagicwizard** [MagicTheGathering/mtg-sdk-dotnet#43]
Hello

I don't know what's going on but the All() is missing everywhere!!!

My program has more then 200 calls to All() and it does not compile anymore.

Would you be so kind to put All() back everywhere so I can continue to make my program? That code worked perfectly.

I'm a beginner and have no knowledge of Async and threads etc etc... I'm making a very simple program that uses All() to get the result. I have no experience with threads and also don't need this in my program. I just wait until mouse cursor is set to normal again in my code after All() has finished.

I'm very sad now, development of my program is stopped because of 2 reasons:

- .NET 4 support is dropped
- All() is removed

I hope you put it back. I worked for months on this program.

Best regards
Jessica

**Comment by jregnier** [comment]
I really don't want to add the non-asynchronous method calls back into the library, they were an example of bad coding and should be removed. You should not be using synchronous code for getting data from a Web API. if you really don't want to make your program asynchronous then you can always add a .Result to the end of the AllAsync method, although this is a major code smell.

I will be adding multi targets though

**Comment by ancientmagicwizard** [comment]
So AllAsync().Result you mean? If I run it this way, does it block the current thread?

Is a Backgroundworker a correct way to run your AllAsync?

see: 

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker?view=net-5.0

Thx for adding multi targets!!!

**Comment by jregnier** [comment]
No that's the old way of doing thing things. You need to use await and async keywords

**Comment by ancientmagicwizard** [comment]
I understand AllAsync() runs in a different thread and when called does not block the thread it was called in , in my case the UI thread.

If this is'correct, in which way do I need to call AllAsync:

- in a new thread
- in a new Task

?

My program's user interface must know when AllAsync() is completed.
When I used All() the UI thread was blocked and when All() had finished its work, I updated my UI.

So if'you can explain what way to use (thread or task) in order to know when AllAsync() has completed.

thx

**Comment by ancientmagicwizard** [comment]
I never used a async call, so that's why I ask.

Maybe you can write an example which you include in the library source code in 'examples' of how a user can get all sets using AllAsync() with a way to know when the AllAsync() has completed its work?

If I run AllAsync().Result , does it block the thread it is called in (so my UI thread)?
I didn't understand?

**Comment by jregnier** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/async

**Comment by ancientmagicwizard** [comment]
Will you never remove .Result in an update?
Because I want to use it now.

**Comment by jregnier** [comment]
yes
