### ISSUE TITLE
protection level: inaccessible

### ISSUE THREAD

**Issue by ghost** [MagicTheGathering/mtg-sdk-dotnet#45]
Hi

Many classes are not accessible, here are some errors I get:

'Card' is inaccessible due to its protection level

'Set' is inaccessible due to its protection level

'SetService' is inaccessible due to its protection level

'SetService.AllAsync()' is inaccessible due to its protection level

'CardService' is inaccessible due to its protection level

Also properties of Set give the same error:

'Set.Name' is inaccessible due to its protection level
(and some other properties of Set)

Those all worked in the previous nuget package.

**Comment by ancientmagicwizard** [comment]
These errors I got in a test program in .NET 5.0 because the nuget package can't be installed in .NET 4.8

**Comment by jregnier** [comment]
that is by design, everything returned will be an interface now which is used to make the object immutable. The fact that you could set a model property was a bad design. Look at the updated README

**Comment by ancientmagicwizard** [comment]
Please write code examples how to do everything!!!

How do'i get all sets?
How do i get all cards from a set?

You just broke my whole program.
I don't know what you mean

Nothings works

**Comment by ancientmagicwizard** [comment]
how to read a card if i can't even use 'Card'?

fucking asshole

DONT TOUCH THE LIBRARY
EVERYTHING IS BROKEN NOW!!!!!!

**Comment by ancientmagicwizard** [comment]
I want examples of

- how to get all sets and get set information

- how to get all cards from a set and get all card info

- how to do a query and get all cards for'it


write them and stop'destroying everything

and make a package for .net 4

FUCKING MORON
