### ISSUE TITLE
.NET Framework 4.8: incompatible nuget package

### ISSUE THREAD

**Issue by ghost** [MagicTheGathering/mtg-sdk-dotnet#46]
Hi

When trying to install the new nuget package in .NET Framework 4.8, I get following error.
I believe you must target .NET Standard 2.0 instead of 2.1.

According to this website .NET Framework does not support .NET Standard 2.1

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Could not install package 'MtgApiManager.Lib 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		

(installing in .NET 5.0 works successfully)

**Comment by ancientmagicwizard** [comment]
MAKE THE PACKAGE SO IT'WORKS

OR I KICK YOUR ASS

FAGGOT
