### ISSUE TITLE
release date bug?

### ISSUE THREAD

**Issue by the-namelessone** [MagicTheGathering/mtg-sdk-dotnet#48]
Hello,

I just updated my software using latest nuget, but I saw the following value is not filled in, while it was in previous versions.
It's now an empty string. 

ISet.ReleaseDate

greetz

**Comment by bmeijwaard** [comment]
Found issue on `MtgApiManager.Lib.Dto.SetDto` line 38 should be camelcase ( `[JsonPropertyName("ReleaseDate")]` )

**Comment by the-namelessone** [comment]
Thx! I wait untill it's changed.

**Comment by jregnier** [comment]
@bmeijwaard can you not push a pull request?

**Comment by bmeijwaard** [comment]
@jregnier no, git keeps giving me 403 permission denied on both https and ssh. I made a bug branch according to github convention, but unable to push the branch to origin.

**Comment by jregnier** [comment]
hmm interesting let me see if I have the power to give permissions or if something changed

**Comment by jregnier** [comment]
is it possible that your system is storing the GitHub credentials, possibly need to be cleared? I don't have access to the settings since they are at the org level.

**Comment by jregnier** [comment]
could be worth trying this http://raaviblog.com/how-to-resolve-git-push-command-related-permission-error/

**Comment by jregnier** [comment]
If not I can push up a change

**Comment by bmeijwaard** [comment]
I was able to create a pull request thru a fork.

**Comment by the-namelessone** [comment]
Can you release a new nuget package?

**Comment by bmeijwaard** [comment]
No, that is up to @jregnier if the pull request gets approved.

**Comment by jregnier** [comment]
I'll release a new NuGet package soon since there are a few other bugs I would like in there.

This is why this library needs the tests to be redone ;)

closing issue
