### ISSUE TITLE
ISet vs Set, ICard vs Card

### ISSUE THREAD

**Issue by the-namelessone** [MagicTheGathering/mtg-sdk-dotnet#49]
Hello,

I see the way to get Set and Card info is now done using a ISet and ICard.
I was wondering why this change was made?
Because it's still doing the same, for example I get ISet.Code or ICard.Name etc.
It does exactly the same as in the old version.

What is the reason for this change?

greetz

**Comment by jregnier** [comment]
I made a change to make things more encapsulated. So that the consumer never sees the implementation details. So you are right that the objects are exactly the same but the interface is immutable now.

let me know if this causing any issues, I can try and work around it.

**Comment by the-namelessone** [comment]
Thanks, understood.
