### ISSUE TITLE
Can't get results with a multiverse ID of a german card

### ISSUE THREAD

**Issue by MichaelScherf** [MagicTheGathering/mtg-sdk-dotnet#5]
I'm trying to get card data about a german version of a card, for example "abundant maw".
Multiverse id of english card is 414290 -> result is not null, IsSuccess is true

For the german version, I use service.Find(414959), but it returns false and no result.
Is this an issue or a limitation? How to get the german card name, text and flavor text?

thanks for any help.

P.S. I didn't get any answer in facebook or via email. Is this project dead?

**Comment by MichaelScherf** [comment]
I just made some changes in the code:
I added a new JsonProperty "multiverseid" in CardQueryParameter.cs, and changed the cardService.Where(c => c.MultiVerseId...). Now it is still working for a multiverse id of an english card. With a german id, the result.IsSucess is true, but the value has Count = 0.

**Comment by jregnier** [comment]
After looking into this it looks like it's the baking API that is determining this. in the English response, there is a "foreignNames" section when the German name exists.

**Comment by MichaelScherf** [comment]
Hi,

Yes, I already found this German name, but would like to get ALL german texts from the card (type, flavor, etc.)

I guess, at the moment, this is not possible.

Regards, Michael
