### ISSUE TITLE
query result wrong

### ISSUE THREAD

**Issue by the-namelessone** [MagicTheGathering/mtg-sdk-dotnet#61]
Hi

I updated to latest nuget package.
I don't know what's going on: is it a bug in the library or a server problem, but if you run this query and read the card data, everything is wrong. 

- If you want set code "ALL", you get cards from "10E" set

var cardRequest = serviceProvider.GetCardService().Where(x => x.Set, "ALL");

- if you do this query, you get cards from "10E" too

var cardRequest = serviceProvider.GetCardService().Where(x => x.Set, "ICE");

- if you do this query, you get cards from "10E" too

var cardRequest = serviceProvider.GetCardService().Where(x => x.Set, "ATQ");

No matter what query you do, the result are always the same "10E" cards...

Can you check if this is a bug in the library?

**Comment by the-namelessone** [comment]
I used the older nuget package too and this worked correctly.
This problem occured after updating so I think it's a serious bug now.

Thx for the help!

**Comment by jregnier** [comment]
so I took a look and ran the following query and they were all correct, not sure 
`ICardService cardService = _serviceProvider.GetCardService();`
`var result = await cardService.Where(x => x.Set, "ALL").AllAsync();`
`result .Value.All(x => x.Set == "ALL");` this returns true

**Comment by jregnier** [comment]
got the same result when running the query manually
https://api.magicthegathering.io/v1/cards?set=ALL

**Comment by the-namelessone** [comment]
Hi

Please take a look at my code, this code returned the correct cards BEFORE the nuget package update.
Now it returns only "10E" cards no matter what query. String SetCode is filled in by my program.
What's wrong in this code? I really can't find it

async Task GetCardsBySetCode()
        {
            Debug.WriteLine("GetCardsBySetCode START");

            int NrOfCardsRead = 0;
            var cardRequest = serviceProvider.GetCardService().Where(x => x.Set, SetCode);
            Exceptional<List<ICard>> result = await cardRequest.AllAsync();
          
            int pagesCount = result.PagingInfo.TotalPages;
            int cardCount = result.PagingInfo.TotalCount;
            Console.WriteLine("card count:" + cardCount);
			
            for (int i = 0; i <= pagesCount; i++)
            {
                var page = await cardRequest.Where(p => p.Page, i + 1).AllAsync();

                if (page.IsSuccess)
                {
                    foreach (ICard card in page.Value)
                    {
                        Debug.WriteLine(card.Name);
                        NrOfCardsRead++;

                        CardList.Add(card);
                    }

                    if (NrOfCardsRead == cardCount)
                        Debug.WriteLine("All cards read!");
                }
                else
                {
                    throw page.Exception;
                }
            }

            Debug.WriteLine("GetCardsBySetCode END");
        }

**Comment by bmeijwaard** [comment]
It would be helpful to see how the SetCode variable is filled.

**Comment by the-namelessone** [comment]
I just have a list of all card sets in my program and when double clicked it sets the SetCode to the selected card set's code.

There is no bug in there (I just tested), just replace in my code above SetCode by "ALL" or "ICE", ... and run the task.
You will see it return always "10E" cards no matter what value for SetCode you choose.

This exact same code worked 100% before the nuget package update.
So that's why I think it's strange.

Do you see a mistake in this code?

**Comment by bmeijwaard** [comment]
The issue is related to this fix: https://github.com/MagicTheGathering/mtg-sdk-dotnet/issues/57

First you call an instance of the CardService where the `Set` is set to `SetCode`. Then `AllAsync()` is called. After this trigger the 'reset' which was present in the linked 'fix'.

Then every new request will have no `Set` set anymore and will simply perform the request without the `Set`.

Try changing to:

```
...
var cardRequest = serviceProvider.GetCardService(); // here
Exceptional<List<ICard>> result = await cardRequest.Where(x => x.Set, SetCode).AllAsync(); // here

int pagesCount = result.PagingInfo.TotalPages;
int cardCount = result.PagingInfo.TotalCount;
Console.WriteLine("card count:" + cardCount);

for (int i = 0; i <= pagesCount; i++)
{
    var page = await cardRequest.Where(x => x.Set, SetCode).Where(p => p.Page, i + 1).AllAsync(); // here

...
```

**Comment by the-namelessone** [comment]
Hi

Perfectly working again and I understand it. It's great to have you as contributor!
