### ISSUE TITLE
request: ICard IsColorless

### ISSUE THREAD

**Issue by the-namelessone** [MagicTheGathering/mtg-sdk-dotnet#62]
Hi

Would it be possible to add a new property "IsColorless" to ICard?

Next to IsMultiColor which is already there, we then have a nice clean way to get all card's color properties.

It should do: (ICard.Colors.Length == 0)

Thanks in advance!

**Comment by bmeijwaard** [comment]
Created pull request.

**Comment by the-namelessone** [comment]
thx!

**Comment by jregnier** [comment]
merged! closing issue
