### ISSUE TITLE
question: OriginalType and Type

### ISSUE THREAD

**Issue by the-namelessone** [MagicTheGathering/mtg-sdk-dotnet#66]
Hi

What's the difference between OriginalType and Type of a ICard?

Even with the comments I don't understand it.

**Comment by the-namelessone** [comment]
I'm not sure if it's a bug but I can find cards that have null value for OriginalType , while Type has a value.
Is this a bug or is it normal some cards have null value for OriginalType ?

**Comment by jregnier** [comment]
have you tried to make a call to the web API?

**Comment by the-namelessone** [comment]
no I have no'knowledge of'it

It are the 15 th anniversary cards which have null value

**Comment by jregnier** [comment]
The web API is linked in the readme, the reason I ask is because if the return JSON is the same then it's just the web API but if the data returned is different then it's a bug with the library

**Comment by bmeijwaard** [comment]
From the API docs. `originalType`:
The original type on the card at the time it was printed. This field is not available for promo cards. 

That means types like 'interrupt' or other wordings in Types that have been changed over time. `Counterspell` for example.

Newer don't have that `problem`, so it is most likely null for most cards, except for reprints. Besides, that is no real usage for this information.

**Comment by bmeijwaard** [comment]
As seen in the screenshot, the JSON response for a 15th anniversary card the originalType is absent. Just as the docs stated for Promo cards/sets

![image](https://user-images.githubusercontent.com/31803222/101321689-0a909800-3866-11eb-9c20-13e973da2169.png)

**Comment by the-namelessone** [comment]
thx
