### ISSUE TITLE
Problem getting the list of all sets

### ISSUE THREAD

**Issue by remillaro01** [MagicTheGathering/mtg-sdk-dotnet#74]
It looks like when I'm using the ISetService.AllAsync(), I only get the 500 first sets available, seems like I can't get passed that value, it's not like the ICardService where you can get the different pages, the only available use I can put in my Where clause, is "Block" and "Name", no pages,

result_set = await set_service.AllAsync(); // This give me at most 500 sets, 

Do you have any ideas of how we can get passed that value?

**Comment by jregnier** [comment]
Seems like this might be a bug, I can definitely take a look

**Comment by remillaro01** [comment]
Thank you a lot!

**Comment by KarateSnoopy** [comment]
btw, here's a working example of how to get all the standard cards using that new page/pagesize field.  it writes all the data to local csv files to avoid spamming service getting same data over and over again.

https://pastebin.com/cFrs1nkb

**Comment by remillaro01** [comment]
Thank you very much 😊 i'm putting my card list with my need info in a
localdb from where I use it instead of poking everytime the API 😊

Le dim. 27 mars 2022, 23 h 15, KarateSnoopy ***@***.***> a
écrit :
