### ISSUE TITLE
MultiverseId string?

### ISSUE THREAD

**Issue by lonely-unicorn** [MagicTheGathering/mtg-sdk-dotnet#80]
Hi

In the past the MultiverseId of a ICard was an integer. Now it's suddenly a string.
Why this change? I changed my code but I don't know why this change is made.

**Comment by jregnier** [comment]
This was changed to address a bug found last April

From the API docs
![image](https://user-images.githubusercontent.com/8887814/160726374-10ea6083-903b-480b-85f9-40e29219b10a.png)

**Comment by lonely-unicorn** [comment]
thanks for explaining
