### ISSUE TITLE
missing multiverse IDs: bug?

### ISSUE THREAD

**Issue by ghost** [MagicTheGathering/mtg-sdk-dotnet#81]
Hi

I understand a ICard won't have a  multiverse ID when the card is not on Magic the gathering's gatherer website.
But I found many cases (I think) of cards that exist but still have no multiverse ID.

For example the tenth edition (10E) card set. All cards in this set should be on gatherer, right?

Please look at the screenshot and see how many cards in this set have no multiverse ID.

![afbeelding](https://user-images.githubusercontent.com/101529915/161401635-fd3587d3-a10a-47dd-ae15-828e2737b559.png)

Look at card "angel of mercy". There exist 2 cards: one with number 2 and one with number 2 "star". I think the 2 cards are the same but have just another art. (see many more examples in the screenshot). 
I want to download each different art for each card using Scryfall using the multiverse ID.
All cards with a "star" in the number seem not to have a multiverse ID. So I can't download those cards.

Is this a bug in the API, the SDK wrapper or does gatherer NOT include cards with the same name but other art?
I'm sure I saw the same cards with other art in my magic collection (in many different sets) so this is a bit of a mystery :-)

ps: the screenshot is raw data I got by using the SDK and put in a GUI (nothing changed or edited by myself)

Thanks for the help!

**Comment by billybimbob** [comment]
I believe that the numbers with the star are foil versions of the card, which I would assume Gatherer does not keep track of, hence the lack of the multiverseId and imageUrl attributes.

**Comment by jregnier** [comment]
if you call the api directly with
https://api.magicthegathering.io/v1/cards?name=angel%20of%20mercy
you can see that a few don't have multiverseid.

**Comment by lonely-unicorn** [comment]
Hi

Thanks for the explanation!

However I found more cases for which I don't know an explanation. This time in the 8ED (3 cases have no multiverseID, all other cards have).
Some cards seem to have card number ending with "s" and they don't have a multiverseID.
Does anybody know what those cards are exactly?

![afbeelding](https://user-images.githubusercontent.com/101529915/161447925-40458576-ba07-4b8f-a41e-99d55e20348d.png)

![afbeelding](https://user-images.githubusercontent.com/101529915/161447931-7774b0ab-2799-4c61-a631-1cca0345bd8c.png)

![afbeelding](https://user-images.githubusercontent.com/101529915/161447938-6d20a22d-9e4d-4c50-b608-7fec12604f34.png)

Lisa

**Comment by jregnier** [comment]
sorry, no idea. The lib just takes what the API gives it
