### ISSUE TITLE
PagingInfo always Null

### ISSUE THREAD

**Issue by GodJohnson** [MagicTheGathering/mtg-sdk-dotnet#9]
Hi,
Just tried PagingInfo, but it's always null.

Am I using it the wrong way ?

```
var service = new CardService();
var result = service.All();

var pagingInfo = result.PagingInfo; 
```

Here, pagingInfo is always null

**Comment by jregnier** [comment]
Just took and look and found the bug will put up a fix for that. Thanks for letting me know

**Comment by jregnier** [comment]
Bug is fixed and also uploaded new Nuget package
